# Generated by Django 2.1.1 on 2018-09-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('end_date', models.DateField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='services_approved',
        ),
        migrations.RenameModel(
            old_name='Approverlist',
            new_name='Approver',
        ),
        migrations.RenameModel(
            old_name='Servicelist',
            new_name='Services',
        ),
        migrations.DeleteModel(
            name='Userlist',
        ),
        migrations.AddField(
            model_name='user',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ras_app.Approver'),
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(to='ras_app.Services'),
        ),
    ]
