# Generated by Django 2.2.4 on 2019-08-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountscreator',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='accountscreator',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='approver',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='approver',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='requestordetails',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='requestordetails',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='last_name',
        ),
    ]
