# Generated by Django 2.1.1 on 2018-10-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0002_auto_20181012_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ras_app.Request')),
            ],
        ),
    ]
