# Generated by Django 2.2.4 on 2019-08-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0002_auto_20190816_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='token',
        ),
    ]
