# Generated by Django 2.1.1 on 2018-10-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0002_auto_20181008_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
