# Generated by Django 2.1.1 on 2018-09-19 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0003_auto_20180919_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
