# Generated by Django 2.1.1 on 2018-10-11 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0003_auto_20181008_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('surname', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('services', models.ManyToManyField(to='ras_app.Services')),
            ],
        ),
    ]
