# Generated by Django 2.1.1 on 2018-12-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0004_remove_requestordetails_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='additional_info',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
