# Generated by Django 2.1.1 on 2018-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0004_request_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='token',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
