# Generated by Django 2.1.1 on 2018-10-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0004_accountscreator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='services',
        ),
    ]
