# Generated by Django 2.1.1 on 2018-12-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0005_services_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='additional_info',
        ),
    ]
