# Generated by Django 2.1.1 on 2018-10-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0005_remove_request_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(null=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ras_app.Request')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ras_app.Services')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='services',
            field=models.ManyToManyField(through='ras_app.RequestServices', to='ras_app.Services'),
        ),
    ]
