# Generated by Django 2.1.1 on 2018-12-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0006_remove_services_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='additional_info',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
