# Generated by Django 2.1.1 on 2018-09-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0006_auto_20180922_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
