# Generated by Django 2.1.1 on 2018-10-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0006_auto_20181011_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestservices',
            old_name='request_id',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='requestservices',
            old_name='service_id',
            new_name='service',
        ),
    ]
