# Generated by Django 2.1.1 on 2018-09-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0007_request_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='request',
        ),
        migrations.AddField(
            model_name='user',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ras_app.Request'),
            preserve_default=False,
        ),
    ]
