# Generated by Django 2.1.1 on 2018-12-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0008_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='team',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ras_app.Teams'),
            preserve_default=False,
        ),
    ]
