# Generated by Django 2.1.1 on 2018-12-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0009_request_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ras_app.Teams'),
            preserve_default=False,
        ),
    ]
