# Generated by Django 2.1.1 on 2018-12-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0010_auto_20181224_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='sc',
            field=models.BooleanField(default=False),
        ),
    ]
