# Generated by Django 2.1.1 on 2019-07-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0011_teams_sc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='end_date',
        ),
    ]
