# Generated by Django 2.1.1 on 2019-07-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ras_app', '0012_remove_user_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_docs',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.CharField(default=False, max_length=400),
        ),
    ]
